pool: 'Hosted Windows 2019 with VS2019'

trigger:
  batch: 'true'
  branches:
    include:
    - master
    - develop

pr:
  branches:
    include:
    - master
    - develop

variables:
  NuGetArtifactName: Packages
  NuGetToolVersion: 5.8.0

stages:
- stage: Build
  jobs:
  - job: Windows_Build
    steps:
    - task: GitVersion@5
      displayName: 'Calculate version'

    - task: MSBuild@1
      displayName: 'Build solution in Release | Any CPU'
      inputs:
        solution: src\NvGet.sln
        configuration: Release
        platform: 'Any CPU'
        msbuildArguments: >
         /p:PackageVersion=$(GitVersion.NuGetVersion)
         /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
         /p:GeneratePackageOnBuild=true
         /r

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(NuGetArtifactName)
      displayName: 'Publish NuGet packages'

- stage: Release
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  - deployment: NuGet
    environment: NuGet
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(NuGetArtifactName)

          - task: NuGetToolInstaller@1
            displayName: 'Use NuGet $(NuGetToolVersion)'
            inputs:
              versionSpec: $(NuGetToolVersion)
        
          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: 'NuGet.org - nventive'
              packagesToPush: $(Pipeline.Workspace)/$(NuGetArtifactName)/*.nupkg
                
