name: CI

on: 
  push:
    branches:
      - develop
      - master

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master
      
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
